### ISSUE TITLE
LastaFlute example repository not found

### ISSUE THREAD

**Issue by yu1ro** [seasarorg/dbflute-www#3]
On http://dbflute.seasar.org/ja/lastaflute/

The single lastaflute project example [repository](https://github.com/dbflute-session/lastaflute-example-maihama.git)
is not found.
Where is this repository?

**Comment by yu1ro** [comment]
I found it.
https://github.com/lastaflute/lastaflute-example-maihama

**Comment by jflute** [comment]
The single lastaflute project example repository is here:
https://github.com/lastaflute/lastaflute-example-harbor.git

http://dbflute.seasar.org/ja/lastaflute/#singletrial

but multi-project is also good example.
dockside is HTML style
hangar is JSON API style

**Comment by yu1ro** [comment]
Thank you for your reply.

But, I mean there are many broken links in doc.

**Comment by jflute** [comment]
Oh, exactly...

I fixed several links now, thank you.
